name: goreleaser

on:
  push:
    branches: ["main"]

permissions:
  contents: write
    
jobs:
  create-git-tag:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v2
       - name: Create git tag
         run: |
           echo "v$(date +%Y.%m.%d.%H.%M.%S)" > TAG_NAME
           git tag $(cat TAG_NAME)
           git push origin $(cat TAG_NAME)

  goreleaser:
    runs-on: ubuntu-latest
    needs: create-git-tag
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
