name: Go Test with MySQL

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.28
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: template
          MYSQL_USER: docker
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Install dependencies
        run: go mod download

      - name: Set environment variables
        run: |
          echo "DB_USER=docker" >> $GITHUB_ENV
          echo "DB_PASSWORD=password" >> $GITHUB_ENV
          echo "DB_HOST=localhost" >> $GITHUB_ENV
          echo "DB_PORT=3306" >> $GITHUB_ENV
          echo "DB_NAME=template" >> $GITHUB_ENV

      - name: Run tests
        run: go test ./...
